### ISSUE TITLE
Fix OS Release Comparing: 8.10

### ISSUE THREAD

**Issue by jrmetzger** [mitre/redhat-enterprise-linux-8-stig-baseline#43]
```
# Waiting on: https://github.com/mitre/redhat-enterprise-linux-8-stig-baseline/pull/39
SV-230221:
  justification: This should pass since 8.10 is in correct time, need to account for 8.10 and 8.1 - RHEL 8 must be a vendor-supported release.
  run: false
SV-250316:
  justification: This should not be running on 8.10 - RHEL 8 systems below version 8.2 must configure SELinux context type to allow the use of a non-default faillock tally directory.
  run: false
SV-230332:
  justification: This should not be running on 8.10 - RHEL 8 must automatically lock an account when three unsuccessful logon attempts occur.
  run: false
SV-230338:
  justification: This should not be running on 8.10 - RHEL 8 must ensure account lockouts persist.
  run: false
SV-230342:
  justification: This should not be running on 8.10 - RHEL 8 must log user name information when unsuccessful logon attempts occur.
  run: false
SV-230344:
  justification: This should not be running on 8.10 - RHEL 8 must include root when automatically locking an account until the locked account is released by an administrator when three unsuccessful logon attempts occur during a 15-minute time period.
  run: false
```
