### ISSUE TITLE
Files are correct but Inspec isn't parsing right

### ISSUE THREAD

**Issue by jrmetzger** [mitre/redhat-enterprise-linux-8-stig-baseline#44]
```
SV-230423:
  justification: Line is correct, but Inspec not parsing correctly - Successful/unsuccessful uses of the mount command in RHEL 8 must generate an audit record.
  run: false
SV-230466:
  justification: Line is correct, but Inspec not parsing correctly - Successful/unsuccessful modifications to the faillock log file in RHEL 8 must generate an audit record.
  run: false
SV-230345:
  justification: Line is correct, but Inspec not parsing correctly - RHEL 8 must include root when automatically locking an account until the locked account is released by an administrator when three unsuccessful logon attempts occur during a 15-minute time period.'
  run: false
SV-230251:
  justification: Line is correct, but Inspec not parsing correctly - The RHEL 8 SSH server must be configured to use only Message Authentication Codes (MACs) employing FIPS 140-2 validated cryptographic hash algorithms.
  run: false
SV-230228:
  justification: Line is correct, but Inspec not parsing correctly - All RHEL 8 remote access methods must be monitored.
  run: false
SV-237643:
  justification: Only once in /etc/sudoers and /etc/sudoers/* - RHEL 8 must require re-authentication when using the "sudo" command.
  run: false
SV-230484:
  justification: Duplicating the line to check for some reason? - RHEL 8 must securely compare internal information system clocks at least every 24 hours with a server synchronized to an authoritative time source, such as the United States Naval Observatory (USNO) time servers, or a time server designated for the appropriate DoD network (NIPRNet/SIPRNet), and/or the Global Positioning System (GPS).
  run: false
```
